### ISSUE TITLE
adjustments to moo for import/export compatibility

### ISSUE THREAD

**Issue by lisp** [no-context/moo#113]
what approach is intended to use moo in a browser via export/import
i found this note in the nearley playground, but it remains unresolved:

    https://github.com/bijection/nearley-playground/issues/16

i have read also the nearley note about "compiling in browsers"

    https://nearley.js.org/docs/using-in-frontend

but that does not indicate how to adjust the process to use moo as a lexer and also does not mention how to handle export/import.

**Comment by tjvr** [comment]
I'm not sure we have enough information to answer your question.

There are lots of tools to get JavaScript into a browser, even if the JS uses imports: for example rollup, webpack, or browserify. Moo doesn't mind what you use.

Maybe this is a question about compiling Nearley grammars?

The Nearley Playground is a special case, since it lets you write grammars containing JavaScript in the browser.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lisp** [comment]
i suppose, what i am hoping to do is not to have to bundle it, but instead to generate a lexer which works with export/import.

**Comment by tjvr** [comment]
You should be able to include the moo JS file in your page, and then use `var moo = window.moo` in your Nearley grammar instead of require().  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
